import 'package:dio/dio.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:game_tracker/core/network/api_client.dart';
import 'package:game_tracker/features/auth/domain/auth_repository.dart';
import 'package:game_tracker/features/auth/data/repositiories/firebase_auth_repository_impl.dart';
import 'package:game_tracker/features/auth/presentation/bloc/login_bloc.dart';
import 'package:game_tracker/features/games/data/models/local_game.dart';
import 'package:game_tracker/features/games/data/repositories/game_repository_impl.dart';
import 'package:game_tracker/features/games/domain/game_repository.dart';
import 'package:game_tracker/features/games/presentation/bloc/game_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:isar_community/isar.dart';
import 'package:path_provider/path_provider.dart';


final sl = GetIt.instance;

Future<void> _initIsar() async {
  final dir = await getApplicationDocumentsDirectory();
  final isar = await Isar.open(
    [LocalGameSchema], // Generated by isar_generator
    directory: dir.path,
  );
  sl.registerSingleton<Isar>(isar);

}


Future<void> init() async {
  // Register with GetIt
  // Repository
  await _initIsar();
  GoogleSignIn.instance.initialize(
    serverClientId: '490063376002-au8b40tqmbkqaku721oerad5a08as06q.apps.googleusercontent.com', // needed for idToken
  );

  sl.registerLazySingleton(() => Dio());
  sl.registerLazySingleton(() => ApiClient(sl()));
  sl.registerLazySingleton(() => GoogleSignIn.instance);

  sl.registerLazySingleton<AuthRepository>(() => FirebaseAuthRepository(sl(), sl()));
  sl.registerLazySingleton<GameRepository>(() => GameRepositoryImpl(sl(), sl()));

  // BLoC (Using registerFactory for BLoCs, to get a fresh one per screen)
  sl.registerFactory(() => LoginBloc(sl()));
  sl.registerFactory(() => GameBloc(sl()));

  // External
  sl.registerLazySingleton(() => FirebaseAuth.instance);
}