import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dio/dio.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:game_tracker/core/cache/cache_metadata.dart';
import 'package:game_tracker/core/network/api_client.dart';
import 'package:game_tracker/features/auth/domain/auth_repository.dart';
import 'package:game_tracker/features/auth/data/repositiories/firebase_auth_repository_impl.dart';
import 'package:game_tracker/features/auth/presentation/bloc/login_bloc.dart';
import 'package:game_tracker/features/game_details/data/datasources/game_details_local_data_source.dart';
import 'package:game_tracker/features/games/data/datasources/game_local_data_source.dart';
import 'package:game_tracker/features/games/data/models/local_filter.dart';
import 'package:game_tracker/features/games/data/models/local_game.dart';
import 'package:game_tracker/features/game_details/data/models/local_game_detail.dart';
import 'package:game_tracker/features/games/data/repositories/discovery_repository_impl.dart';
import 'package:game_tracker/features/games/data/repositories/game_repository_impl.dart';
import 'package:game_tracker/features/games/domain/game_repository.dart';
import 'package:game_tracker/features/games/domain/repositories/discovery_repository.dart';
import 'package:game_tracker/features/game_details/data/repositories/game_details_repository_impl.dart';
import 'package:game_tracker/features/game_details/domain/repositories/game_details_repository.dart';
import 'package:game_tracker/features/game_details/presentation/bloc/game_details_bloc.dart';
import 'package:game_tracker/features/games/presentation/bloc/discovery/discovery_bloc.dart';
import 'package:game_tracker/features/games/presentation/bloc/discovery/discovery_filter_cubit.dart';
import 'package:game_tracker/features/schedule/presentation/bloc/schedule_bloc.dart';
import 'package:game_tracker/features/games/presentation/bloc/company/games_by_company_bloc.dart';
import 'package:game_tracker/features/dashboard/presentation/bloc/dashboard_bloc.dart';
import 'package:game_tracker/features/library/data/datasources/library_local_data_source.dart';
import 'package:game_tracker/features/profile/presentation/bloc/profile_bloc.dart';
import 'package:game_tracker/features/library/data/models/local_library_item.dart';
import 'package:game_tracker/features/library/data/repositories/library_repository_impl.dart';
import 'package:game_tracker/features/library/domain/library_repository.dart';
import 'package:game_tracker/features/library/presentation/bloc/library_bloc.dart';
import 'package:game_tracker/features/library/presentation/cubit/library_filter_cubit.dart';
import 'package:game_tracker/features/settings/data/datasources/settings_local_data_source_impl.dart';
import 'package:game_tracker/features/settings/data/models/user_settings.dart';
import 'package:game_tracker/features/settings/data/datasources/settings_local_data_source.dart';
import 'package:game_tracker/features/settings/data/repositories/settings_repository_impl.dart';
import 'package:game_tracker/features/settings/domain/repositories/settings_repository.dart';
import 'package:game_tracker/features/games/presentation/bloc/genre/genre_games_bloc.dart';
import 'package:game_tracker/features/settings/presentation/bloc/settings_cubit.dart';
import 'package:get_it/get_it.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:isar_community/isar.dart';
import 'package:path_provider/path_provider.dart';

final sl = GetIt.instance;

Future<void> _initIsar() async {
  final dir = await getApplicationDocumentsDirectory();
  final isar = await Isar.open(
    [LocalGameSchema, LocalGameDetailSchema, LocalLibraryItemSchema, LocalFilterSchema, CacheMetadataSchema, UserSettingsSchema], // Generated by isar_generator
    directory: dir.path,
  );
  sl.registerSingleton<Isar>(isar);
}

Future<void> init() async {
  // Repository
  await _initIsar();
  GoogleSignIn.instance.initialize(
    serverClientId: '490063376002-au8b40tqmbkqaku721oerad5a08as06q.apps.googleusercontent.com',
  );

  sl.registerLazySingleton(() => Dio());
  sl.registerLazySingleton(() => ApiClient());
  sl.registerLazySingleton(() => GoogleSignIn.instance);
  sl.registerLazySingleton(() => FirebaseFirestore.instance);

  sl.registerLazySingleton<GameLocalDataSource>(() => GameLocalDataSourceImpl(sl()));
  sl.registerLazySingleton<GameDetailsLocalDataSource>(() => GameDetailsLocalDataSourceImpl(sl()));
  sl.registerLazySingleton<AuthRepository>(() => FirebaseAuthRepository(sl(), sl()));
  sl.registerLazySingleton<GameRepository>(() => GameRepositoryImpl(sl(), sl()));
  sl.registerLazySingleton<DiscoveryRepository>(() => DiscoveryRepositoryImpl(sl(), sl(), sl()));
  sl.registerLazySingleton<GameDetailsRepository>(() => GameDetailsRepositoryImpl(sl(), sl()));
  sl.registerLazySingleton<LibraryLocalDataSource>(() => LibraryLocalDataSourceImpl(sl()));
  sl.registerLazySingleton<LibraryRepository>(() => LibraryRepositoryImpl(sl(), sl(), sl()));
  sl.registerLazySingleton<SettingsLocalDataSource>(() => SettingsLocalDataSourceImpl(sl()));
  sl.registerLazySingleton<SettingsRepository>(() => SettingsRepositoryImpl(sl(), sl()));


  // BLoC (Using registerFactory for BLoCs, to get a fresh one per screen)
  sl.registerFactory(() => LoginBloc(sl()));
  sl.registerFactory(() => ProfileBloc(sl(), sl()));
  sl.registerFactory(() => GameDetailsBloc(sl()));
  sl.registerFactory(() => LibraryFilterCubit());
  sl.registerFactory(() => LibraryBloc(sl()));
  sl.registerLazySingleton(() => DiscoveryFilterCubit());
  sl.registerFactory(() => DiscoveryBloc(repository: sl(), filterCubit: sl()));
  sl.registerFactory(() => ScheduleBloc(repository: sl()));
  sl.registerFactory(() => GenreGamesBloc(repository: sl()));
  sl.registerFactoryParam<GamesByCompanyBloc, DiscoveryFilterCubit, void>(
    (filterCubit, _) => GamesByCompanyBloc(sl(), filterCubit),
  );
  sl.registerFactory(() => SettingsCubit(sl()));
  sl.registerFactory(() => DashboardBloc(libraryRepository: sl(), discoveryRepository: sl()));


  // External
  sl.registerLazySingleton(() => FirebaseAuth.instance);
}